# -*- coding: utf-8 -*-
"""100 yaş hesaplama

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18l67W0pmP19jz6wOjFQhXMBjrwqPTyro
"""

#.Ask user for their name
ad = input("Adın nedir? ").strip().title()


#. Ask user for their age
yas = int(input("Kaç yaşındasın?"))

#. 100 yas hesaplama
yuz_yas_yili = 2025 + (100 - yas)
print(ad, "100 yaşına ", yuz_yas_yili, "yılında gireceksin.")