# -*- coding: utf-8 -*-
"""Calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJQitrM7t2knOzpbh2Y-EfzEcoQwsGm4
"""

x = float(input("Birinci sayıyı gir:"))
y= float(input("ikinci sayıyı gir:"))

toplam = x + y
fark = x - y
carpim = x * y
bolum = x / y

print("Toplam:",toplam)
print("Fark:",fark)
print("Çarpım:",carpim)
print("Bölüm:",bolum)

