# -*- coding: utf-8 -*-
"""Geri sayim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kza3MP7ddlHVAgbE-jHH-atIygi1CTOt
"""

sayi = int(input("Bir sayı giriniz: "))

for i in range(sayi, -1, -1):
    print(i)

print("Ateşle! 🚀")

