# -*- coding: utf-8 -*-
"""Negatif Pozitif

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b--FoMFWLbFo91YMytF6kQ3b2vWYNcX
"""

sayi = float(input("bir sayı giriniz"))
if sayi > 0:
  print("sayı pozitif ")
elif sayi < 0:
  print("sayı negatif")
else:
  print("sayı sıfır.")