# -*- coding: utf-8 -*-
"""Sayi kontrol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185cC6jTjALOmmZ3SKM_ShqWDLPfdNeQR
"""

try:
    sayi = int(input("Bir sayı giriniz: "))
    print("Girdiğiniz sayı:", sayi)
except ValueError:
    print("Lütfen geçerli bir sayı giriniz")