# -*- coding: utf-8 -*-
"""Sınav Notu hesaplayıcı

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxHQcmiaPPiFk7Q3BERiTSRPbA5dxZa6
"""

notu = float(input("Lütfen sınav notunuzu girin: "))
if notu > 50:
  print("Geçti :)")
else:
  print("Kaldı :(")