# -*- coding: utf-8 -*-
"""Toplam Hesaplayici

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk96kSCVumtL_Oukt7DzdBCxmXjgXIuD
"""

N = int(input("Bir sayı giriniz: "))

toplam = 0
for i in range(1, N + 1):
    toplam += i

print("Toplam:", toplam)