# -*- coding: utf-8 -*-
"""Vize sayaci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TlZsjWKD7sk5OmAgcfA0_WNH1pjF4rdx
"""

#. Bu programi kendi başıma yazmak için çok çabaladım ama maalesef bazı kısımları gbtden sorarak yaptım
from datetime import datetime

tarih_str = input("Sınav tarihini giriniz (GG/AA/YYYY SS:DD): ")

try:
    sinav_tarihi = datetime.strptime(tarih_str, "%d/%m/%Y %H:%M")
    simdi = datetime.now()

    fark = sinav_tarihi - simdi

    if fark.total_seconds() <= 0:
        print("Bu sınav tarihi geçmiş.")
    else:
        gun = fark.days
        saat = fark.seconds // 3600
        print(f"Sınava {gun} gün {saat} saat kaldı.")
except ValueError:
    print("Lütfen tarihi doğru formatta giriniz (GG/AA/YYYY SS:DD)")